services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./data:/data/db

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-container
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - PYTHONPATH=/project
    volumes:
      - ./machine-learning-client:/project
    working_dir: /project

  web-app:
    build: ./web-app
    container_name: web-app-container
    depends_on:
      - mongodb
      - machine-learning-client
    environment:
      - DB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
      - PYTHONPATH=/project
    volumes:
      - ./web-app:/project
    working_dir: /project
    ports:
      - "8080:8080"
