version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-container
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    command: >
      sh -c "while ! nc -z mongodb-container 27017; do sleep 1; done && python3 app.py"
    ports:
      - "5050:5050"

  web-app:
    build: ./web-app
    container_name: web-app-container
    depends_on:
      - mongodb
      - machine-learning-client
    environment:
      - DB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
    ports:
      - "8080:8080"
    command: >
      sh -c "while ! nc -z ml-container 5050; do sleep 1; done && python3 app.py"

volumes:
  mongodb-data:
