version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb-container

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-container
    depends_on:
      - mongodb
    env_file:
        - .env
    command: python3 app.py

  web-app:
    build: ./web-app
    container_name: web-app-container
    depends_on:
      - mongodb
      - machine-learning-client
    env_file:
      - .env
    command: python3 app.py