version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-container
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-container:27017
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    command: ["sh", "-c", "python3 app.py"]
    ports:
      - "5050:5050"

  web-app:
    build: ./web-app
    container_name: web-app-container
    depends_on:
      - mongodb
      - machine-learning-client
    environment:
      - DB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-container:27017
      - SECRET=${SECRET}
    command: ["sh", "-c", "python3 app.py"]
    ports:
      - "8080:8080"

