version: "3.8"

'''
Docker-compose file
Includes DB, ML Client, and Web App
'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  machine-learning-client:
    build: ./machine-learning-client
    container_name: ml-container
    depends_on:
      - mongodb
    environment:
        - DB_URI=${MONGODB_URI}
    command: python3 app.py

  web-app:
    build: ./web-app
    container_name: web-app-container
    depends_on:
      - mongodb
      - machine-learning-client
    environment:
      - DB_URI=${MONGODB_URI}
    ports:
      - "8080:8080"
    command: python3 app.py